import { NextResponse } from 'next/server'
import { writeFile, mkdir } from 'fs/promises'
import { join } from 'path'
import { existsSync } from 'fs'

const WEB_DIR = join(process.cwd(), 'forge-output', 'web')

const HTML_TEMPLATE = (theme: string, palette: string[]) => `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${theme.toUpperCase()} — Kai Asset Forge</title>
  <link href="https://fonts.googleapis.com/css2?family=VT323&display=swap" rel="stylesheet">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      background: #0a0c12;
      color: #e2e8f0;
      font-family: 'VT323', monospace;
      min-height: 100vh;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      background-image:
        repeating-linear-gradient(0deg, transparent, transparent 2px, rgba(0,0,0,0.03) 2px, rgba(0,0,0,0.03) 4px);
    }
    .card {
      background: #12151d;
      border: 2px solid ${palette[0] || '#f5a623'};
      padding: 40px;
      max-width: 600px;
      text-align: center;
      box-shadow: 0 0 40px ${palette[0] || '#f5a623'}22;
    }
    h1 {
      font-size: 48px;
      letter-spacing: 4px;
      color: ${palette[0] || '#f5a623'};
      text-shadow: 0 0 20px ${palette[0] || '#f5a623'}55;
      margin-bottom: 10px;
    }
    .subtitle {
      font-size: 18px;
      color: #475569;
      letter-spacing: 3px;
      margin-bottom: 24px;
    }
    .palette-row {
      display: flex;
      gap: 8px;
      justify-content: center;
      margin: 20px 0;
    }
    .swatch {
      width: 32px; height: 32px;
      border: 2px solid #252938;
      image-rendering: pixelated;
    }
    .tag {
      display: inline-block;
      background: ${palette[0] || '#f5a623'}15;
      border: 1px solid ${palette[0] || '#f5a623'}44;
      color: ${palette[0] || '#f5a623'};
      padding: 4px 10px;
      font-size: 14px;
      letter-spacing: 1px;
      margin: 4px;
    }
    .footer {
      margin-top: 30px;
      font-size: 12px;
      color: #252938;
      letter-spacing: 2px;
    }
    .pulse {
      display: inline-block;
      width: 8px; height: 8px;
      background: #4ade80;
      animation: blink 1s step-end infinite;
      margin-right: 8px;
    }
    @keyframes blink { 0%,100%{opacity:1} 50%{opacity:0} }
  </style>
</head>
<body>
  <div class="card">
    <h1>${theme.toUpperCase()}</h1>
    <div class="subtitle">✦ KAI ASSET FORGE ✦</div>
    <p style="font-size: 16px; color: #94a3b8; letter-spacing: 1px;">
      A ${theme}-themed landing page, forged by the Web Generator agent.
    </p>
    <div class="palette-row">
      ${palette.map(c => `<div class="swatch" style="background:${c}" title="${c}"></div>`).join('\n      ')}
    </div>
    <div>
      <span class="tag">${theme}</span>
      <span class="tag">HERMES OS v5</span>
      <span class="tag">FORGE</span>
    </div>
    <div class="footer">
      <span class="pulse"></span> GENERATED BY WEB GENERATOR · KAI ASSET FORGE
    </div>
  </div>
</body>
</html>`

export async function POST(request: Request) {
  try {
    const body = await request.json().catch(() => ({}))
    const theme = body.theme || 'dungeon'
    const feature = body.feature || 'landing-page'

    const palettes: Record<string, string[]> = {
      dungeon: ['#f5a623', '#e94560', '#0f3460', '#16213e', '#1a1a2e'],
      fantasy: ['#c084fc', '#4ade80', '#2d1b4e', '#1e3a5f', '#f5a623'],
      scifi: ['#22d3ee', '#7c3aed', '#1e1b4b', '#0a0a1a', '#e2e8f0'],
      nature: ['#4ade80', '#166534', '#3b82f6', '#1a2e1a', '#f5a623'],
    }
    const palette = palettes[theme.toLowerCase()] || palettes.dungeon

    if (!existsSync(WEB_DIR)) {
      await mkdir(WEB_DIR, { recursive: true })
    }

    const ts = Date.now()
    const filename = `${theme}-${feature}-${ts}.html`
    const filepath = join(WEB_DIR, filename)
    const html = HTML_TEMPLATE(theme, palette)
    await writeFile(filepath, html, 'utf-8')

    return NextResponse.json({
      success: true,
      asset: {
        name: `${theme}-${feature}`,
        filename,
        path: `/api/library/image?file=${encodeURIComponent(`web/${filename}`)}`,
        category: 'web',
        type: feature,
        size: Buffer.byteLength(html, 'utf-8'),
        palette,
      },
    })
  } catch (e: any) {
    return NextResponse.json({ success: false, error: e.message }, { status: 500 })
  }
}
